spring:
  datasource:
    data-username: root
    data-password: 920722lhb
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      #会根据映射实体类自动创建或更新数据
      ddl-auto: update
      #在控制台打印出sql语句
    show-sql: true
    #指定创建数据库的类型为Innodb(支持事务管理),如果不指定默认为myiSAM(不支持事务管理)
    database-platform: org.hibernate.dialect.MySQL57Dialect
  main:
    allow-bean-definition-overriding: true
